name: Build QUEEN OS for Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            quilt
            parted
            qemu-user-static
            debootstrap
            zerofree
            dosfstools
            e2fsprogs
            libarchive-tools
            libcap2-bin
            grep
            bc
            gpg
            xxd
            arch-test
            bmap-tools
            kmod
          version: 1.0

      - name: Cache stage0
        id: cache_stage0
        uses: actions/cache@v4
        with:
          path: work
          key: pigen-stage0-${{ hashFiles('stage0/**') }}
          restore-keys: |
            pigen-stage0-

      - name: Build stage0
        if: ${{ steps.cache_stage0.outputs.cache-hit != 'true' }}
        env:
          STAGE_LIST: "stage0"
        run: |
          sudo ./build.sh

      - name: Result files
        run: ls -R work