name: Build QUEEN OS for Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: |
            quilt
            parted
            qemu-user-static
            debootstrap
            zerofree
            dosfstools
            e2fsprogs
            libarchive-tools
            libcap2-bin
            grep
            bc
            gpg
            xxd
            arch-test
            bmap-tools
            kmod
          version: 1.0