name: Build QUEEN OS for Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add sudo permissions for tar
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

      - name: Install APT dependencies
        run: sudo apt install -y quilt parted qemu-user-static debootstrap zerofree dosfstools e2fsprogs libarchive-tools libcap2-bin grep bc gpg xxd arch-test bmap-tools kmod

      - name: Cache lite system
        id: cache_lite
        uses: actions/cache@v4
        with:
          path: ./work
          key: pigen-${{ runner.os }}-lite-${{ hashFiles('stage0/**', 'stage1/**', 'stage2/**', 'config') }}
          restore-keys: |
            pigen-${{ runner.os }}-lite-

      - name: Build lite system
        if: steps.cache_lite.outputs.cache-hit != 'true'
        run: |
          echo "IMG_NAME='queenos'" > config
          touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
          touch ./stage2/SKIP_IMAGES ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES
          sudo ./build.sh