name: Build QUEEN OS for Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add sudo permissions for tar
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

      - name: Install APT dependencies
        run: sudo apt install -y quilt parted qemu-user-static debootstrap zerofree dosfstools e2fsprogs libarchive-tools libcap2-bin grep bc gpg xxd arch-test bmap-tools kmod

      - name: Create config
        run: |
          cat > config << EOF
          IMG_NAME='queenos'
          EOF

      - name: Restore lite system cache
        uses: actions/cache/restore@v4
        id: restore_cache_lite
        with:
          path: ./work
          key: pigen-${{ runner.os }}-lite-${{ hashFiles('stage0/**', 'stage1/**', 'stage2/**', 'config') }}

      - name: Build lite system
        id: build_lite
        if: steps.restore_cache_lite.outputs.cache-hit != 'true'
        run: |
          touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP ./stage6/SKIP
          touch ./stage2/SKIP_IMAGES ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES ./stage6/SKIP_IMAGES
          sudo ./build.sh
          echo "Cleanup"
          find ./stage* -name "SKIP*" -print -delete
          sudo rm -rf ./work/*/stage0 ./work/*/stage1
          
      - name: Save lite system cache
        uses: actions/cache/save@v4
        id: save_cache_lite
        if: steps.restore_cache_lite.outputs.cache-hit != 'true'
        with:
          path: ./work
          key: pigen-${{ runner.os }}-lite-${{ hashFiles('stage0/**', 'stage1/**', 'stage2/**', 'config') }}

      - name: Restore desktop system cache
        uses: actions/cache/restore@v4
        id: restore_cache_desktop
        with:
          path: ./work
          key: pigen-${{ runner.os }}-desktop-${{ hashFiles('stage0/**', 'stage1/**', 'stage2/**', 'stage3/**', 'stage4/**', 'config') }}

      - name: Build desktop system
        id: build_desktop
        if: steps.restore_cache_desktop.outputs.cache-hit != 'true' && (steps.restore_cache_lite.outputs.cache-hit == 'true' || steps.build_lite.outcome == 'success')
        run: |
          touch ./stage0/SKIP ./stage1/SKIP ./stage2/SKIP ./stage5/SKIP ./stage6/SKIP
          touch ./stage2/SKIP_IMAGES ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES ./stage6/SKIP_IMAGES
          sudo ./build.sh
          echo "Cleanup"
          find ./stage* -name "SKIP*" -print -delete
          sudo rm -rf ./work/*/stage2 ./work/*/stage3

      - name: Save desktop system cache
        uses: actions/cache/save@v4
        id: save_cache_desktop
        if: steps.restore_cache_desktop.outputs.cache-hit != 'true'
        with:
          path: ./work
          key: pigen-${{ runner.os }}-desktop-${{ hashFiles('stage0/**', 'stage1/**', 'stage2/**', 'stage3/**', 'stage4/**', 'config') }}

      - name: Build and export system
        run: |
          touch ./stage0/SKIP ./stage1/SKIP ./stage2/SKIP ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
          touch ./stage2/SKIP_IMAGES ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES ./stage6/SKIP_IMAGES
          echo "STAGE_LIST='stage0 stage1 stage2 stage3 stage4 stage6'" >> config
          sudo ./build.sh
          echo "Cleanup"
          find ./stage* -name "SKIP*" -print -delete
          sudo rm -rf ./work/*/stage2 ./work/*/stage4

      - name: Export system
        run: |
          touch ./stage0/SKIP ./stage1/SKIP ./stage2/SKIP ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP ./stage6/SKIP
          touch ./stage2/SKIP_IMAGES ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES
          echo "STAGE_LIST='stage6'" >> config
          sudo ./build.sh
          echo "Cleanup"
          find ./stage* -name "SKIP*" -print -delete

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          path: deploy/*.*
          if-no-files-found: error
